name = "exercism"
version = "1.0.0"

description = "Exercism Journey with Gleam Language"
licences = ["MIT"]
repository = { type = "github", user = "abroudoux", repo = "https://github.com/abroudoux/exercism-gleam" }

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleam_regexp = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
